# Generated by Django 3.2.7 on 2021-09-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='product_img',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_type',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
    ]
