# Generated by Django 3.2.7 on 2021-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0002_auto_20210917_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_mrp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_number',
            field=models.TimeField(),
        ),
    ]
